apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: products-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/yogithak25/e-commerce-store.git
    targetRevision: main
    path: helm-charts/products-service

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
