name: Products Service CI/CD
on:
  push:
    branches:
      - main
    paths:
      - 'products-cna-microservice/**'
      - 'helm-charts/products-service/**'
      - '.github/workflows/products-ci-cd.yml'
env:
  IMAGE_NAME: yogithak/products-service

jobs:
  products-ci-cd:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./products-cna-microservice

    steps:

    # STEP 1 - Checkout Repository
    - name: Checkout Source Code
      uses: actions/checkout@v4

    # STEP 2 - Setup NodeJS
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: products-cna-microservice/package-lock.json

    # STEP 3 - Install Dependencies
    - name: Install Dependencies
      run: npm ci

    # STEP 4 - Run Tests
    - name: Run Unit Tests
      run: npm test || echo "No tests configured"

    # STEP 5 - Build Application
    - name: Build NodeJS Application
      run: npm run build --if-present

    # STEP 6 - DockerHub Login
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # STEP 7 - Build Docker Image
    - name: Build Docker Image
      run: |
        docker build \
        -t $IMAGE_NAME:v1.${{ github.run_number }} .

    # STEP 8 - Push Docker Image
    - name: Push Docker Image
      run: |
        docker push $IMAGE_NAME:v1.${{ github.run_number }}

    # STEP 9 - Update Helm values.yaml
    - name: Update Helm Chart Image Tag
      working-directory: .
      run: |
        sed -i 's/tag:.*/tag: "v1.'"${{ github.run_number }}"'"/' helm-charts/products-service/values.yaml

    # STEP 10 - Commit Updated Helm Chart
    - name: Commit Helm Chart Changes
      working-directory: .
      run: |
        git config --global user.email "yogithak25@gmail.com"
        git config --global user.name "yogithak25"

        git add helm-charts/products-service/values.yaml

        git commit -m "Updated products-service image tag to v1.${{ github.run_number }}" || echo "No changes to commit"

        git push
